<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

/**
 * Retail membership catalog from HERO Memberships pricing 03-2025.pdf
 * (USD list prices; +10% TCA tax applied at checkout — not stored here.)
 * For yearly plans, monthly values enforce a 20% annual-prepay discount:
 * yearly = monthly * 12 * 0.80.
 */
class RetailPlansSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'code' => 'HR-01A',
                'name' => 'Local – Individual',
                'category' => 'retail',
                'tier' => 'local',
                'retail_subgroup' => '10_day',
                'sort_order' => 10,
                'coverage_days' => 10,
                'billing_interval' => 'one_time',
                'commitment_months' => null,
                'price' => 25.00,
                'price_monthly' => null,
                'features' => [
                    'Essential Emergency Protection',
                    '1 In-Country Emergency Air Evacuation ($750 co-pay)',
                    '24/7 Unlimited Access to HERO Emergency Resources',
                    '1 Ground Ambulance Transport',
                    'Patient Advocacy Services for Hospitalization Support',
                    '3rd-Party Injury Coverage',
                ],
                'ideal_for' => 'Local travelers, budget-conscious individuals',
                'included_members' => null,
                'addon_price_yearly' => null,
                'min_members' => null,
                'max_members' => null,
            ],
            [
                'code' => 'HR-01AC',
                'name' => 'VIP – Individual',
                'category' => 'retail',
                'tier' => 'vip',
                'retail_subgroup' => '10_day',
                'sort_order' => 20,
                'coverage_days' => 10,
                'billing_interval' => 'one_time',
                'commitment_months' => null,
                'price' => 41.50,
                'price_monthly' => null,
                'features' => [
                    'Includes all HR-01A Local benefits',
                    'Priority Medical Support & Full Coordination',
                    'Full-Service Medevac Coordination',
                    'HERO Manages All Family Notifications & Insurance Claims',
                    'Coordination of Medical Evacuation to a Hospital in the USA',
                ],
                'ideal_for' => 'Expats, business travelers, high-risk travelers',
                'included_members' => null,
                'addon_price_yearly' => null,
                'min_members' => null,
                'max_members' => null,
            ],
            [
                'code' => 'HR-01B',
                'name' => 'Local – Individual',
                'category' => 'retail',
                'tier' => 'local',
                'retail_subgroup' => '1_month',
                'sort_order' => 30,
                'coverage_days' => 30,
                'billing_interval' => 'one_time',
                'commitment_months' => null,
                'price' => 65.00,
                'price_monthly' => null,
                'features' => [
                    'Access to HERO’s WhatsApp Security Groups',
                    '1 In-Country Emergency Flight Transport ($200 co-pay)',
                    '24/7 Unlimited Access to HERO Emergency Resources',
                    '1 Ground Ambulance Transport',
                    'Patient Advocacy Services',
                    '3rd-Party Coverage',
                ],
                'ideal_for' => null,
                'included_members' => null,
                'addon_price_yearly' => null,
                'min_members' => null,
                'max_members' => null,
            ],
            [
                'code' => 'HR-01BC',
                'name' => 'VIP – Individual',
                'category' => 'retail',
                'tier' => 'vip',
                'retail_subgroup' => '1_month',
                'sort_order' => 40,
                'coverage_days' => 30,
                'billing_interval' => 'one_time',
                'commitment_months' => null,
                'price' => 110.00,
                'price_monthly' => null,
                'features' => [
                    'Includes all HR-01B Local benefits',
                    'Full-Service Medevac Coordination',
                    'HERO Manages All Family Notifications & Insurance Claims',
                    'Coordination of Medical Evacuation to a Hospital in the USA',
                ],
                'ideal_for' => null,
                'included_members' => null,
                'addon_price_yearly' => null,
                'min_members' => null,
                'max_members' => null,
            ],
            [
                'code' => 'HR-02',
                'name' => 'Local – Individual (annual)',
                'category' => 'retail',
                'tier' => 'local',
                'retail_subgroup' => 'annual_individual',
                'sort_order' => 50,
                'coverage_days' => null,
                'billing_interval' => 'yearly',
                'commitment_months' => null,
                'price' => 199.99,
                'price_monthly' => 20.83,
                'features' => [
                    'Exclusive Access to HERO’s WhatsApp Security Groups',
                    '1 Emergency Air Evacuation Within Haiti ($750 co-pay)',
                    '24/7 Unlimited Access to HERO’s Emergency Response Team',
                    '2 Ground Ambulance Transports',
                    'Patient Advocacy Services',
                    '3rd-Party Injury Coverage',
                ],
                'ideal_for' => null,
                'included_members' => null,
                'addon_price_yearly' => null,
                'min_members' => null,
                'max_members' => null,
            ],
            [
                'code' => 'HR-02C',
                'name' => 'VIP – Individual (annual)',
                'category' => 'retail',
                'tier' => 'vip',
                'retail_subgroup' => 'annual_individual',
                'sort_order' => 60,
                'coverage_days' => null,
                'billing_interval' => 'yearly',
                'commitment_months' => null,
                'price' => 398.98,
                'price_monthly' => 41.56,
                'features' => [
                    'Includes all benefits of the Local Plan',
                    'No Co-Pay on Air Evacuations',
                    'Unlimited Emergency Air Evacuations',
                    'Priority Medical Transfers & Seamless Hospital Coordination',
                    'HERO Handles All Insurance & Family Notifications',
                    'Concierge Medical Assistance',
                ],
                'ideal_for' => null,
                'included_members' => null,
                'addon_price_yearly' => null,
                'min_members' => null,
                'max_members' => null,
            ],
            [
                'code' => 'HR-03',
                'name' => 'Local – Family (annual)',
                'category' => 'retail',
                'tier' => 'local',
                'retail_subgroup' => 'annual_family',
                'sort_order' => 70,
                'coverage_days' => null,
                'billing_interval' => 'yearly',
                'commitment_months' => null,
                'price' => 325.00,
                'price_monthly' => 33.85,
                'features' => [
                    'Covers up to 4 family members',
                    'Exclusive Access to HERO’s WhatsApp Security Groups',
                    '2 In-Country Emergency Air Evacuations per Family (subject to co-pay)',
                    '24/7 Unlimited Access to HERO’s Emergency Response Team',
                    '5 Ground Ambulance Transports',
                    'Patient Advocacy Services',
                    '3rd-Party Injury Coverage',
                    'Add additional family members: $32.00/year per person, up to 6 total family members',
                ],
                'ideal_for' => null,
                'included_members' => 4,
                'addon_price_yearly' => 32.00,
                'min_members' => null,
                'max_members' => 6,
            ],
            [
                'code' => 'HR-03C',
                'name' => 'VIP – Family (annual)',
                'category' => 'retail',
                'tier' => 'vip',
                'retail_subgroup' => 'annual_family',
                'sort_order' => 80,
                'coverage_days' => null,
                'billing_interval' => 'yearly',
                'commitment_months' => null,
                'price' => 637.00,
                'price_monthly' => 66.35,
                'features' => [
                    'Includes all Local Plan benefits',
                    '2 In-Country Emergency Air Evacuations per Family (no co-pay)',
                    'Full-Service Medevac Coordination',
                    'HERO Handles All Family Notifications & Insurance Claims',
                    'Coordination of Medical Evacuation to a U.S. Hospital',
                    'Add additional family members: $122.00/year per person, up to 6 total family members',
                ],
                'ideal_for' => null,
                'included_members' => 4,
                'addon_price_yearly' => 122.00,
                'min_members' => null,
                'max_members' => 6,
            ],
        ];

        foreach ($rows as $row) {
            Plan::updateOrCreate(
                ['code' => $row['code']],
                array_merge($row, ['currency' => 'USD', 'active' => true])
            );
        }
    }
}
