<div class="space-y-4 text-xs leading-relaxed text-slate-600">
    <section>
        <h3 class="mb-2 font-semibold uppercase tracking-wide text-slate-800">Part 1 — Limitation of Liability</h3>
        <p class="mb-2"><strong>1.1 Disclaimer.</strong> THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE”. HERO DISCLAIMS ALL TERMS, CONDITIONS, GUARANTEES, REPRESENTATIONS AND WARRANTIES (EXPRESS, IMPLIED, STATUTORY AND OTHERWISE), IN RESPECT OF THE SERVICES, INCLUDING THOSE OF MERCHANT-ABILITY, NON-INFRINGEMENT, TITLE, QUALITY AND FITNESS FOR A PARTICULAR PURPOSE.</p>
        <p class="mb-2"><strong>1.2 Limitation of Liability.</strong> THE CUSTOMER USES THE SERVICES AT ITS OWN RISK. HERO WILL NOT BE LIABLE FOR ANY LOSS IN CONNECTION TO THE USE OF, OR INABILITY TO USE THE SERVICES, INCLUDING ANY LOSS TO THE CUSTOMER’S DATA. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AND WITHOUT LIMITING THE PREVIOUS SENTENCE, HERO WILL NOT BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES WHATSOEVER IN CONNECTION WITH THE SERVICES.</p>
        <p class="mb-2"><strong>1.3 Maximum Liability.</strong> IF, DESPITE THE ABOVE LIMITATIONS, HERO BECOMES LIABLE TO THE CUSTOMER IN RESPECT OF THE SERVICES OR A COMBINATION OF THE FOREGOING, THAT LIABILITY WILL BE LIMITED TO THE FEES THE CUSTOMER PAID TO HERO FOR ITS USE OF THE SERVICES IN THE 3 MONTHS PRIOR TO THE EVENT GIVING RISE TO THE LIABILITY.</p>
        <p class="mb-2"><strong>1.4 False Alarms or Abuse of Service.</strong> Customer agrees to use the Service with reasonable care so as to avoid the incidence of false alarms. HERO reserves the right to determine the nature and frequency of false alarms in order to independently assess the frequency that may constitute a breach of contract by the Customer, and HERO may cancel this Agreement and the Service. If a false alarm fine or penalty or a response fee is charged to HERO or the Customer by any governmental agency or other person, Customer will pay such charge. Customer further acknowledges and agrees that the Service may be suspended for excessive false alarms, improper calls and “problem accounts.”</p>
        <p><strong>1.5 Downtime.</strong> HERO will use commercially reasonable efforts to keep the Services available 24 hours a day, 7 days a week; however, the Services may occasionally be unavailable due to routine maintenance, emergency maintenance, upgrades, hardware and software malfunctions, repairs, power outages, hackers, denial of service attacks and unforeseeable large service demands. Where reasonably possible, HERO will provide the Customer with prior notice of any scheduled service interruptions.</p>
    </section>

    <section>
        <h3 class="mb-2 font-semibold uppercase tracking-wide text-slate-800">Part 2 — Services</h3>
        <p class="mb-2"><strong>2.1 Services.</strong> Provided that the Customer complies with its obligations under this agreement, HERO will provide the Services to the Customer. HERO may use third party contractors to provide some or all of the Services. The Service is intended to be used only for personal emergencies and the HERO Emergency Dispatch Call Center may notify appropriate authorities (i.e., police, fire department or other emergency personnel) if a call is received from the Customer and the HERO Emergency Dispatch Call Center verifies such call.</p>
        <p><strong>2.2 Limitations.</strong> IN CONSIDERATION FOR THE PROVISION OF THE SERVICE, CUSTOMERS ACKNOWLEDGES THAT NEITHER HERO NOR ANY OF OUR SUPPLIERS OR SUBCONTRACTORS REPRESENT OR WARRANT THAT THE SERVICE WILL PREVENT DEATH, BODILY OR PERSONAL INJURY, OR ANY OTHER INJURY OR DAMAGE TO CUSTOMERS OR OTHERS WHO USE THE SERVICE AND CUSTOMERS OR OTHERS WHO USE THE SERVICE DO NOT AND HAVE NOT RELIED UPON ANY EXPRESS OR IMPLIED REPRESENTATION BY HERO OR ANY SUPPLIERS OR SUBCONTRACTORS TO THAT EFFECT. HERO MAKES NO REPRESENTATION OR WARRANTY AS TO THE PROMPTNESS OF THE RESPONSE, AND HERO HAS NO CONTROL OVER THE RESPONSE TIME OR CAPABILITY OF ANY AGENCY OR PERSON WHO MAY BE NOTIFIED AS A RESULT OF THE SERVICE BEING USED. CUSTOMER FURTHER UNDERSTANDS THAT HERO MAY BE NEGLIGENT IN PROVIDING THE SERVICE, AND THE HERO MAY FAIL TO PROPERLY RESPOND TO THE RECEIPT OF AN EMERGENCY CALL FROM ANY DEVICE, OR THAT THE DEVICE MAY FAIL TO FUNCTION PROPERLY. IT IS UNDERSTOOD THAT A PORTION OF THE SERVICE RELIES UPON THE AVAILABILITY OF GPS COVERAGE, WIRELESS INTERNET NETWORK AVAILABILITY AND/OR CELLULAR NETWORK COVERAGE TO OPERATE PROPERLY AS WELL AS THE AVAILABILITY OF SATELLITE GPS DATA, BOTH OF WHICH ARE PROVIDED BY A THIRD PARTY THAT IS NOT CONTROLLED BY HERO. CUSTOMER AGREES THAT IF HERO WERE TO HAVE ANY LIABILITY GREATER THAN THAT AGREED TO BY CUSTOMER PURSUANT TO PART 8 OF THIS AGREEMENT, HERO COULD NOT AND WOULD NOT PROVIDE THE SERVICE. CUSTOMER ACKNOWLEDGES THAT THE CUSTOMER SHOULD OBTAIN ANY LIFE, MEDICAL OR DISABILITY INSURANCE FOR THE PROTECTION OF ALL PERSONS WHO MAY USE THE SERVICE. CUSTOMER UNDERSTANDS THAT THERE ARE ALTERNATIVES AVAILABLE AND THE CUSTOMER HAS SELECTED THIS SERVICE WITH A FULL UNDERSTANDING OF ITS LIMITATIONS, AND THE LIMITATION OF LIABILITY SET FORTH IN PART 8. CUSTOMER AGREES THAT HERO IS RESPONSIBLE ONLY FOR ENDEAVORING TO NOTIFY THE APPROPRIATE RESPONDERS AND IS NOT RESPONSIBLE FOR THE PROMPTNESS, SUFFICIENCY OR ADEQUACY OF THE ACTION OF ANY RESPONDER OR ANY THIRD PARTY ACTING AS A RESPONDER. CUSTOMER ACKNOWLEDGES THAT IN NO WAY DOES HERO REPRESENT OR GUARANTEE THAT THE RESPONDERS CAN BE CONTACTED, THAT THEY CAN OR WILL RESPOND, OR THAT ANY RESPONSE WILL BE SAFE OR EFFECTIVE.</p>
    </section>

    <section>
        <h3 class="mb-2 font-semibold uppercase tracking-wide text-slate-800">Part 3 — General</h3>
        <p class="mb-2"><strong>3.1 Reference.</strong> HERO may refer to the Customer as a customer in HERO's promotional materials, including on HERO's website, and may use the Customer's name and logo (if applicable) for that purpose. HERO may also place a link from its website to the Customer's website.</p>
        <p class="mb-2"><strong>3.2 Law and Courts.</strong> This agreement and each of the documents contemplated by or delivered under or in connection with this agreement are governed exclusively by, and will be enforced, construed and interpreted exclusively in accordance with, the laws applicable in the sovereign nation Haiti. All disputes under this agreement will be resolved by the courts of the sovereign nation of Haiti; however, nothing in this section prohibits either party from obtaining an injunction against the other party in any other jurisdiction.</p>
        <p class="mb-2"><strong>3.3 Severability.</strong> Each provision of this agreement is severable. If any provision of this agreement is or becomes illegal, invalid or unenforceable in any jurisdiction, the illegality, invalidity or unenforceability of that provision will not affect the legality, validity or enforceability of the remaining provisions of this agreement, or of that provision in any other jurisdiction.</p>
        <p class="mb-2"><strong>3.4 Assignment.</strong> The Customer must not assign this agreement or its rights or obligations under this agreement to any third party, except with the prior written consent of HERO.</p>
        <p class="mb-2"><strong>3.5 Renewal.</strong> After the Initial Term, this agreement will automatically renew the HERO Enterprise License fees for an unlimited number of yearly renewal terms unless a party gives the other party written notice of non-renewal at least 30 days prior to the end of the then-current term. After the Initial Term, the Service Level Agreement will terminate, but a new Service Level Agreement may be formed independent of the continuity of HERO Enterprise License fee renewals.</p>
        <p><strong>3.6 No Other Rights.</strong> All rights not expressly granted in this agreement are reserved by HERO. For clarity, nothing in this agreement will be construed as granting the Customer any ownership, security, right in any intellectual property, or other rights in or relating to any or all of the Services.</p>
    </section>

    <section>
        <h3 class="mb-2 font-semibold uppercase tracking-wide text-slate-800">Part 4 — Confidentiality &amp; Proprietary Rights</h3>
        <p class="mb-2"><strong>4.1 Confidentiality.</strong> Each party will (and will cause its employees and agents to) keep the other party’s Confidential Information strictly confidential, and will not: (a) use it or take any benefit from it except as required to perform or receive the Services, or (b) disclose it to anyone unless the other party consents or unless the recipient is required by law or court order to do so. In this agreement, “Confidential Information” means all information, data and financial information relating to the business, commercial strategies, pricing, personnel, customers, products or services of a party.</p>
        <p class="mb-2"><strong>4.2 Customer Data.</strong> As between the parties, HERO solely owns all the Customer’s data in the Services (the “Customer Data”). HERO may manipulate, format, display, transmit and otherwise use that data as necessary to perform its obligations under this agreement and to provide the Services to the Customer.</p>
        <p class="mb-2"><strong>4.3 Security.</strong> The Customer must keep its password and user name for the Services confidential. The Customer must not allow any third party access or use its user name, password or account for the Services. The Customer is solely responsible and liable for all activity conducted through its account in connection with the Services. If the Customer becomes aware of or reasonably suspects any security breach, including any loss, theft or unauthorized disclosure or use of its password or account, the Customer must immediately report the actual or suspected security breach to HERO.</p>
        <p class="mb-2"><strong>4.4 Eligibility.</strong> The eligible participants for a family plan are: The primary, the spouse, and the children who depend upon the parents for support. The children must be under nineteen years of age. If over nineteen they will not be enrolled unless they are full time students at a school, a college or University. In all cases, the insurance for the children will terminate when they reach the age limit of 23. Children of the primary and spouse shall include biological children and step-children, foster children that depend upon support and live in a regular parent-child relationship.</p>
        <p><strong>4.5 Mandatory International Concierge.</strong> It is mandatory that all Families and/or individuals that have an international insurance with medical evacuation, must also have the ‘International Concierge Service Plan’ additional to the local plan. HERO may charge up to $10,000.00 for a medical evacuation coordination fee to a client who does not have international concierge. This fee does not include cost of the medical evacuation, only the coordination. The customer must have a valid international insurance that covers medical evacuation to be eligible for International Concierge.</p>
    </section>
</div>
